services:
  backend:
    build: ./backend
    container_name: klaris-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  db:
    image: ankane/pgvector:latest
    container_name: klaris-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: klaris-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
